CREATE TABLE users (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	firstname VARCHAR(50) DEFAULT NULL,
	lastname VARCHAR(50) DEFAULT NULL,
	email VARCHAR(80) NOT NULL,
	phonenumber1 VARCHAR(30) DEFAULT NULL,
	phonenumber2 VARCHAR(30) DEFAULT NULL,
	comment VARCHAR(255) DEFAULT NULL,
	doc DATETIME NOT NULL DEFAULT NOW()
);